"""empty message

Revision ID: 1efc004142fb
Revises: 73936d247adc
Create Date: 2020-02-17 05:54:44.192825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1efc004142fb'
down_revision = '73936d247adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('honeymoon_funds')
    op.add_column('wedding_registries', sa.Column('fund', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wedding_registries', 'fund')
    op.create_table('honeymoon_funds',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('registry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('target_amount', mysql.FLOAT(), nullable=True),
    sa.Column('has_achieved_target', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_target_achieved', mysql.DATETIME(), nullable=True),
    sa.Column('has_been_paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_paid_status_updated', mysql.DATETIME(), nullable=True),
    sa.Column('admin_updated_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`has_achieved_target` in (0,1))', name='honeymoon_funds_chk_1'),
    sa.CheckConstraint('(`has_been_paid` in (0,1))', name='honeymoon_funds_chk_2'),
    sa.ForeignKeyConstraint(['admin_updated_id'], ['user.id'], name='honeymoon_funds_ibfk_1'),
    sa.ForeignKeyConstraint(['registry_id'], ['wedding_registries.id'], name='honeymoon_funds_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
