"""empty message

Revision ID: 379a6cdbaaf7
Revises: e12cc5ad7900
Create Date: 2020-02-21 01:20:39.659149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379a6cdbaaf7'
down_revision = 'e12cc5ad7900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_bundle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('is_bundle', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_bundle')
    op.drop_table('product_bundle_items')
    # ### end Alembic commands ###
