"""empty message

Revision ID: 3980c377a244
Revises: 5247a2f62366
Create Date: 2020-02-16 17:00:48.448501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3980c377a244'
down_revision = '5247a2f62366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry_delivery_addresses', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.drop_column('registry_delivery_addresses', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry_delivery_addresses', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
    op.drop_column('registry_delivery_addresses', 'full_name')
    # ### end Alembic commands ###
