"""empty message

Revision ID: 3bd4bab81bb4
Revises: 43942bd7a43f
Create Date: 2019-12-20 19:03:51.597823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bd4bab81bb4'
down_revision = '43942bd7a43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honeymoon_funds', sa.Column('message', sa.Text(), nullable=True))
    op.drop_column('honeymoon_funds', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honeymoon_funds', sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True))
    op.drop_column('honeymoon_funds', 'message')
    # ### end Alembic commands ###
