"""empty message

Revision ID: 43942bd7a43f
Revises: 8ecd4eb58691
Create Date: 2019-12-20 19:01:29.737343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43942bd7a43f'
down_revision = '8ecd4eb58691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('honeymoon_funds', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=True)
    op.alter_column('honeymoon_funds', 'target_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('honeymoon_funds', 'target_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('honeymoon_funds', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               nullable=False)
    # ### end Alembic commands ###
