"""empty message

Revision ID: 5272c11a54ec
Revises: 5cbe90603446
Create Date: 2020-01-18 12:11:48.937970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5272c11a54ec'
down_revision = '5cbe90603446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'amount')
    # ### end Alembic commands ###
