"""empty message

Revision ID: 7f933ac6d87a
Revises: a760b33cf6b6
Create Date: 2019-12-31 18:05:39.779300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f933ac6d87a'
down_revision = 'a760b33cf6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_paid', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('payment_txn_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_txn_number')
    op.drop_column('orders', 'date_paid')
    # ### end Alembic commands ###
