"""empty message

Revision ID: 848cb5373129
Revises: daa7f721796c
Create Date: 2019-12-30 02:20:27.627950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '848cb5373129'
down_revision = 'daa7f721796c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_2', 'orders', type_='foreignkey')
    op.drop_column('orders', 'registry_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('registry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_2', 'orders', 'registries', ['registry_id'], ['id'])
    # ### end Alembic commands ###
