"""empty message

Revision ID: 8ecd4eb58691
Revises: 766a72bc5847
Create Date: 2019-12-19 09:55:29.997424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ecd4eb58691'
down_revision = '766a72bc5847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registries', 'will_have_fund')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registries', sa.Column('will_have_fund', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
