"""empty message

Revision ID: a5e168a98f1d
Revises: f95b54702221
Create Date: 2020-01-17 16:45:05.035061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e168a98f1d'
down_revision = 'f95b54702221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('registries', sa.Column('hashtag', sa.String(length=50), nullable=True))
    op.add_column('registries', sa.Column('registry_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registries', 'registry_types', ['registry_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registries', type_='foreignkey')
    op.drop_column('registries', 'registry_type_id')
    op.drop_column('registries', 'hashtag')
    op.drop_table('registry_types')
    # ### end Alembic commands ###
