"""empty message

Revision ID: a760b33cf6b6
Revises: 848cb5373129
Create Date: 2019-12-30 03:47:43.047723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a760b33cf6b6'
down_revision = '848cb5373129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discounted_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discounted_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
