"""empty message

Revision ID: e12cc5ad7900
Revises: ba1745921ed4
Create Date: 2020-02-19 18:49:14.726131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12cc5ad7900'
down_revision = 'ba1745921ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('registry_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('registry_type', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'registry_type')
    op.drop_column('orders', 'registry_id')
    # ### end Alembic commands ###
